# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build Ghost

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CC65_HOME: /usr/local/cc65

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Build cc65, attempting to cache prior builds (no specific version is utilized)
    - name: Cache cc65
      id: cache-cc65
      uses: actions/cache@v3
      with:
        path: ${CC65_HOME}/cc65
        key: ${{ runner.os }}-cc65-build
    - if: ${{ steps.cache-cc65.outputs.cache-hit != 'true' }}
      name: Make cc65
      run: |
        sudo mkdir -p ${CC65_HOME}
        git clone https://github.com/cc65/cc65.git
        cd cc65
        make PREFIX=${CC65_HOME}
        sudo make install

    - name: Setup PATH
      run: echo "${CC65_HOME}/bin" >> ${GITHUB_PATH}
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs/GhostBasic-*.jar
        if-no-files-found: error
